### **Multiple Linear regression**

**Probalem Statement**

Predict the expected salary offering to a candidate for given experience (in years), test score and interview score.

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('C:\Vikram\Datasets\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience.fillna('zero', inplace = True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
 med = df['test_score(out of 10)'].median()
df['test_score(out of 10)'].fillna(med, inplace = True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
from word2number import w2n

In [6]:
def convert(l):
    df = []
    for i in l:
        df.append(w2n.word_to_num(i))
    return df

In [7]:
df.experience = convert(df.experience)
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [8]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [9]:
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
y = df['salary($)']

In [10]:
reg = linear_model.LinearRegression()
reg.fit(X,y)
print("Regression coefficients are:", reg.coef_)
print("Regression intercept is:", reg.intercept_)

Regression coefficients are: [2812.95487627 1845.70596798 2205.24017467]
Regression intercept is: 17737.263464337688


**Que:** Find the expected offering salary for a candidate with 2 years experience, 9 test score, 6 interview score

In [11]:
reg.predict([[2,9,6]])

array([53205.96797671])

**Que:** Find the expected offering salary for a candidate with 12 years experience, 10 test score, 10 interview score

In [12]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [13]:
y_pred = reg.predict(X)
y_pred

array([52350.0727802 , 45734.35225619, 58312.95487627, 63872.63464338,
       67270.74235808, 61148.47161572, 76069.1411936 , 79241.63027656])

In [14]:
from sklearn import metrics
metrics.mean_absolute_error(y_pred,y)

1788.3915574963576